spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/curso-kotlin-spring

    username: postgres
    password: eaocalle32
    initialization-mode: always
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

