insert into PROMOCAO VALUES(1, 'ROMARIA', FALSE, 'APARECIDA DO NORTE', 100.00, 7);
insert into PROMOCAO VALUES(2, 'VIAGEM PRAIA', FALSE, 'CABO FRIO', 400.00, 5);
insert into PROMOCAO VALUES(3, 'CAMINHADA NOTURNA', FALSE, 'JUIZ DE FORA', 50.00, 1);